[package]
name = "assembly"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_yaml = "0.9.34-deprecated"
serde = { version = "1.0.215", features = ["derive"] }
clap = { version = "4.5.21", features = ["derive"] }
bitvec = { version = "1.0.1", features = ["serde"] }